name: vortiqen_models
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.15.1
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.14.0
